Юхатский Илья
urfu-2018/markup-task-8 pull request #74
Opened 2018-12-15 10:29 UTC by creewick

[Посмотреть решение](https://hruview.herokuapp.com/creewick/markup-task-8/master/index.html)

2018-12-15 10:30 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-12-15 10:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-16 15:42 UTC, SemyonMakhaev requested changes
🍅 

1. Поезд движется равномерно, но колёса крутятся неравномерно
2. Поезд должен полностью скрываться за сценой, появляться и исчезать за её краем
3. У паровоза и рельсов перспектива не такая, как на исходном видео, записал скринкаст: https://yadi.sk/i/R16UEro24vnltw
4. При сильном увеличении облаков дыма иконки становятся немного шакалистыми (

Анимацию вращения сцены сделал круто, у меня работает отлично 👍

2018-12-19 07:02 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-12-19 07:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-19 13:29 UTC, SemyonMakhaev requested changes
🍅 

Нашёл вот такой артефакт: https://yadi.sk/i/Er6VbX6we-0hOg
С этой рамкой вокруг сцены две проблемы при вращении:
1. Она не скрывает поезд
2. Она скрывает углы сцены, это тоже немного видно на видео

Кажется, что ограничивающая рамка должна просто участвовать в перспективе, а в остальном всё ок :)

2019-01-12 05:24 UTC, closed without merging